const cards = [
  { key: '2s', rankValue: 1, suitValue: 1, rank: 'Deuce', suit: 'Spade' },
  { key: '3s', rankValue: 2, suitValue: 1, rank: 'Three', suit: 'Spade' },
  { key: '4s', rankValue: 3, suitValue: 1, rank: 'Four', suit: 'Spade' },
  { key: '5s', rankValue: 4, suitValue: 1, rank: 'Five', suit: 'Spade' },
  { key: '6s', rankValue: 5, suitValue: 1, rank: 'Six', suit: 'Spade' },
  { key: '7s', rankValue: 6, suitValue: 1, rank: 'Seven', suit: 'Spade' },
  { key: '8s', rankValue: 7, suitValue: 1, rank: 'Eight', suit: 'Spade' },
  { key: '9s', rankValue: 8, suitValue: 1, rank: 'Nine', suit: 'Spade' },
  { key: 'Ts', rankValue: 9, suitValue: 1, rank: 'Ten', suit: 'Spade' },
  { key: 'Js', rankValue: 10, suitValue: 1, rank: 'Jack', suit: 'Spade' },
  { key: 'Qs', rankValue: 11, suitValue: 1, rank: 'Queen', suit: 'Spade' },
  { key: 'Ks', rankValue: 12, suitValue: 1, rank: 'King', suit: 'Spade' },
  { key: 'As', rankValue: 13, suitValue: 1, rank: 'Ace', suit: 'Spade' },

  { key: '2h', rankValue: 1, suitValue: 2, rank: 'Deuce', suit: 'Heart' },
  { key: '3h', rankValue: 2, suitValue: 2, rank: 'Three', suit: 'Heart' },
  { key: '4h', rankValue: 3, suitValue: 2, rank: 'Four', suit: 'Heart' },
  { key: '5h', rankValue: 4, suitValue: 2, rank: 'Five', suit: 'Heart' },
  { key: '6h', rankValue: 5, suitValue: 2, rank: 'Six', suit: 'Heart' },
  { key: '7h', rankValue: 6, suitValue: 2, rank: 'Seven', suit: 'Heart' },
  { key: '8h', rankValue: 7, suitValue: 2, rank: 'Eight', suit: 'Heart' },
  { key: '9h', rankValue: 8, suitValue: 2, rank: 'Nine', suit: 'Heart' },
  { key: 'Th', rankValue: 9, suitValue: 2, rank: 'Ten', suit: 'Heart' },
  { key: 'Jh', rankValue: 10, suitValue: 2, rank: 'Jack', suit: 'Heart' },
  { key: 'Qh', rankValue: 11, suitValue: 2, rank: 'Queen', suit: 'Heart' },
  { key: 'Kh', rankValue: 12, suitValue: 2, rank: 'King', suit: 'Heart' },
  { key: 'Ah', rankValue: 13, suitValue: 2, rank: 'Ace', suit: 'Heart' },

  { key: '2c', rankValue: 1, suitValue: 3, rank: 'Deuce', suit: 'Club' },
  { key: '3c', rankValue: 2, suitValue: 3, rank: 'Three', suit: 'Club' },
  { key: '4c', rankValue: 3, suitValue: 3, rank: 'Four', suit: 'Club' },
  { key: '5c', rankValue: 4, suitValue: 3, rank: 'Five', suit: 'Club' },
  { key: '6c', rankValue: 5, suitValue: 3, rank: 'Six', suit: 'Club' },
  { key: '7c', rankValue: 6, suitValue: 3, rank: 'Seven', suit: 'Club' },
  { key: '8c', rankValue: 7, suitValue: 3, rank: 'Eight', suit: 'Club' },
  { key: '9c', rankValue: 8, suitValue: 3, rank: 'Nine', suit: 'Club' },
  { key: 'Tc', rankValue: 9, suitValue: 3, rank: 'Ten', suit: 'Club' },
  { key: 'Jc', rankValue: 10, suitValue: 3, rank: 'Jack', suit: 'Club' },
  { key: 'Qc', rankValue: 11, suitValue: 3, rank: 'Queen', suit: 'Club' },
  { key: 'Kc', rankValue: 12, suitValue: 3, rank: 'King', suit: 'Club' },
  { key: 'Ac', rankValue: 13, suitValue: 3, rank: 'Ace', suit: 'Club' },

  { key: '2d', rankValue: 1, suitValue: 4, rank: 'Deuce', suit: 'Diamond' },
  { key: '3d', rankValue: 2, suitValue: 4, rank: 'Three', suit: 'Diamond' },
  { key: '4d', rankValue: 3, suitValue: 4, rank: 'Four', suit: 'Diamond' },
  { key: '5d', rankValue: 4, suitValue: 4, rank: 'Five', suit: 'Diamond' },
  { key: '6d', rankValue: 5, suitValue: 4, rank: 'Six', suit: 'Diamond' },
  { key: '7d', rankValue: 6, suitValue: 4, rank: 'Seven', suit: 'Diamond' },
  { key: '8d', rankValue: 7, suitValue: 4, rank: 'Eight', suit: 'Diamond' },
  { key: '9d', rankValue: 8, suitValue: 4, rank: 'Nine', suit: 'Diamond' },
  { key: 'Td', rankValue: 9, suitValue: 4, rank: 'Ten', suit: 'Diamond' },
  { key: 'Jd', rankValue: 10, suitValue: 4, rank: 'Jack', suit: 'Diamond' },
  { key: 'Qd', rankValue: 11, suitValue: 4, rank: 'Queen', suit: 'Diamond' },
  { key: 'Kd', rankValue: 12, suitValue: 4, rank: 'King', suit: 'Diamond' },
  { key: 'Ad', rankValue: 13, suitValue: 4, rank: 'Ace', suit: 'Diamond' }
];

module.exports = cards;
